# Generated by Django 3.0.5 on 2020-04-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_id',
            fields=[
                ('PLAYER_ID', models.TextField(primary_key=True, serialize=False)),
                ('PLAYER_NAME', models.TextField()),
                ('TEAM_ABBREVIATION', models.TextField()),
                ('AGE', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('YEAR', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shot_data',
            fields=[
                ('PLAYER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Player_id')),
                ('LOC_X', models.IntegerField()),
                ('LOC_Y', models.IntegerField()),
                ('SHOT_ATTEMPTED_FLAG', models.IntegerField()),
                ('SHOT_MADE_FLAG', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player_id',
            name='SEASON',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
        ),
    ]
