# Generated by Django 3.0.5 on 2020-04-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_id',
            name='AGE',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='player_id',
            name='PLAYER_ID',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player_id',
            name='PLAYER_NAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player_id',
            name='SEASON',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
        ),
        migrations.AlterField(
            model_name='player_id',
            name='TEAM_ABBREVIATION',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='season',
            name='YEAR',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
