# Generated by Django 3.0.5 on 2020-04-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200414_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_id',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot_data',
            name='SEASON',
            field=models.ForeignKey(default=0, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot_data',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player_id',
            name='PLAYER_ID',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shot_data',
            name='PLAYER_ID',
            field=models.CharField(max_length=25),
        ),
    ]
