# Generated by Django 3.0.5 on 2020-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_id_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot_data',
            name='SHOT_DISTANCE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
