# Generated by Django 3.0.5 on 2020-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shot_data_shot_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot_data',
            name='ACCURACY_FROM_ZONE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot_data',
            name='ZONE_NAME',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
