# Generated by Django 3.0.5 on 2020-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200416_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot_data',
            name='ACCURACY_FROM_ZONE',
            field=models.FloatField(),
        ),
    ]
