# Generated by Django 2.2.4 on 2020-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200417_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot_data',
            name='TOTALS',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
